import nodemailer from "nodemailer";

import SMTPTransport from "nodemailer/lib/smtp-transport";

const transporter = nodemailer.createTransport({
  host: "smtp.gmail.com",
  port: 465,
  secure: true,
  family: 4, // Forces IPv4 resolution for Render
  auth: {
    user: process.env.EMAIL_USER,
    pass: process.env.EMAIL_PASS,
  },
} as SMTPTransport.Options);

export interface OrderEmailDetails {
  toEmail: string;
  orderId: string;
  productTitle: string;
  price: number;
  deliveryCity: string;
  dispatchedFrom: string;
  distanceKm: number;
  estimatedDays: number;
  paymentId: string;
}

export const sendOrderConfirmationEmail = async (
  details: OrderEmailDetails
): Promise<boolean> => {
  try {
    const mailOptions = {
      from: `"Agentic Commerce Engine" <${process.env.EMAIL_USER}>`,
      to: details.toEmail,
      subject: `Order Confirmation - #${details.orderId.slice(-8)}`,
      html: `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #e0e0e0; border-radius: 8px;">
          <h2 style="color: #4F46E5;">Order Confirmed! 🎉</h2>
          <p>Hi there,</p>
          <p>Thank you for your purchase via <strong>Agentic Commerce Engine</strong>. Your payment was processed successfully.</p>
          
          <hr style="border: none; border-top: 1px solid #eee; margin: 20px 0;" />
          
          <h3 style="color: #333;">Order Details</h3>
          <p><strong>Order ID:</strong> ${details.orderId}</p>
          <p><strong>Product:</strong> ${details.productTitle}</p>
          <p><strong>Total Paid:</strong> ₹${details.price.toLocaleString("en-IN")}</p>
          <p><strong>Payment ID:</strong> ${details.paymentId}</p>
          
          <hr style="border: none; border-top: 1px solid #eee; margin: 20px 0;" />
          
          <h3 style="color: #333;">Fulfillment Logistics</h3>
          <p><strong>Delivery Location:</strong> ${details.deliveryCity}</p>
          <p><strong>Dispatched From:</strong> ${details.dispatchedFrom} (${details.distanceKm} km away)</p>
          <p><strong>Estimated Delivery:</strong> Within ${details.estimatedDays} business days</p>

          <br />
          <p style="font-size: 12px; color: #777; margin-top: 20px;">This is an automated receipt generated by your AI Agent.</p>
        </div>
      `,
    };

    const info = await transporter.sendMail(mailOptions);
    console.log("ORDER_EMAIL_SENT: Message ID ->", info.messageId);
    return true;
  } catch (error) {
    console.error("ORDER_EMAIL_ERROR: Failed to send email ->", error);
    return false;
  }
};
